DBHost = '192.168.30.199'
DBPort = '3306'
DBUser = 'root'
DBPwd = 'vipdatacenter'
DB = 'fifedu_book'

listPath = 'E:\work\fifedu\fifedu_book\list'
detailPath = 'E:\work\fifedu\fifedu_book\detail'
coverPath = 'E:\work\fifedu\fifedu_book\cover'

