DBHost = '192.168.30.199'
DBPort = '3306'
DBUser = 'root'
DBPwd = 'vipdatacenter'
DB = 'fifedu_video'

listPath = 'E:\work\fifedu\fifedu_video\list'
detailPath = 'E:\work\fifedu\fifedu_video\detail'
coverPath = 'E:\work\fifedu\fifedu_video\cover'
