DBHost = '192.168.30.199'
DBPort = '3306'
DBUser = 'root'
DBPwd = 'vipdatacenter'
DB = 'nantong'

USER = 'suhong'

redisHost = '192.168.30.36'
redisPort = '6379'
redisDb = '0'

big_jsonPath = 'E:\work\xunku\big_json'
