DBHost = '192.168.30.199'
DBPort = '3306'
DBUser = 'root'
DBPwd = 'vipdatacenter'
DB = 'swjtu_book'

listPath = 'E:\work\swjtu\list'
detailPath = 'E:\work\swjtu\detail'
imagePath = 'E:\work\swjtu\iamge'
